version: "3.9"
services:
  #MongoDb Service
  mongodb:
    container_name: database
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongodb:/data/db
  #App service
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      PORT: 8080
      MONGO_DB_URL: mongodb://database:27017/fileStorageApi
      MONGO_DB_TEST_URL: mongodb://database:27017/testFileStorageApi
      MAX_FILE_SIZE: 2
      FILE_REMOVE_PERIOD: 59 59 23 * * *
      REMOVE_MAX_AGED_FILE_TIME: 1 * 60 * 60 * 1000
      REQUEST_TIME: 15 * 60 * 1000
      REQUEST_LIMIT: 500
      GCLOUD_PROJECT_ID:
      GCLOUD_STORAGE_BUCKET:
      GCLOUD_EMAIL_CLIENT:
      GCLOUD_PRIVATE_KEY:
    depends_on:
      - mongodb

volumes:
  mongodb: {}
